export const OS_STATUS = {
  RASCUNHO: 'RASCUNHO',
  AGUARDANDO_ACEITE: 'AGUARDANDO_ACEITE',
  ACEITA: 'ACEITA',
  RECUSADA: 'RECUSADA',
  EM_PRODUCAO: 'EM_PRODUCAO',
  PARCIALMENTE_ENTREGUE: 'PARCIALMENTE_ENTREGUE',
  CONFERENCIA: 'CONFERENCIA',
  FINALIZADA: 'FINALIZADA',
  CANCELADA: 'CANCELADA',
} as const;

export type OSStatusType = typeof OS_STATUS[keyof typeof OS_STATUS];

const VALID_TRANSITIONS: Record<string, string[]> = {
  [OS_STATUS.RASCUNHO]: [OS_STATUS.AGUARDANDO_ACEITE, OS_STATUS.CANCELADA],
  [OS_STATUS.AGUARDANDO_ACEITE]: [OS_STATUS.ACEITA, OS_STATUS.RECUSADA, OS_STATUS.CANCELADA, OS_STATUS.RASCUNHO],
  [OS_STATUS.RECUSADA]: [OS_STATUS.RASCUNHO, OS_STATUS.CANCELADA, OS_STATUS.AGUARDANDO_ACEITE],
  [OS_STATUS.ACEITA]: [OS_STATUS.EM_PRODUCAO, OS_STATUS.CANCELADA],
  [OS_STATUS.EM_PRODUCAO]: [OS_STATUS.PARCIALMENTE_ENTREGUE, OS_STATUS.CONFERENCIA, OS_STATUS.FINALIZADA, OS_STATUS.CANCELADA],
  [OS_STATUS.PARCIALMENTE_ENTREGUE]: [OS_STATUS.CONFERENCIA, OS_STATUS.EM_PRODUCAO, OS_STATUS.FINALIZADA, OS_STATUS.CANCELADA],
  [OS_STATUS.CONFERENCIA]: [OS_STATUS.PARCIALMENTE_ENTREGUE, OS_STATUS.EM_PRODUCAO, OS_STATUS.FINALIZADA, OS_STATUS.CANCELADA],
  [OS_STATUS.FINALIZADA]: [],
  [OS_STATUS.CANCELADA]: [],
};

export function canTransitionOS(currentStatus: string, nextStatus: string): boolean {
  if (currentStatus === nextStatus) return true;
  const allowed = VALID_TRANSITIONS[currentStatus];
  return allowed ? allowed.includes(nextStatus) : false;
}
